version: '3'

tasks:
  run-regression:
    desc: Очистка allure-results и запуск regression-тестов
    cmds:
      - python -c "import shutil; shutil.rmtree('./allure-results', ignore_errors=True)"
      - python -m pytest -k "regression" --alluredir=./allure-results